# application-aws.yml
spring:
  datasource:
    url: jdbc:mysql://database-1.cwvgqrxxikpz.ap-northeast-1.rds.amazonaws.com:3306/db-exercise2?useSSL=true&characterEncoding=UTF-8
    username: admin
    password: Likelion1!